services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.11-management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=wad*dr=9RlGl
