services:
  vault:
    image: hashicorp/vault:1.17
    container_name: vault
    restart: always
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "easytrack_token"
    cap_add:
      - IPC_LOCK 
    depends_on:
      - other_service     
