services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: always
    user: root
    ports:
        - "8080:8080"
        - "50000:50000"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   
    networks:
        - devops_net
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    ports:
      - "9090:9090"
    environment:
      SONARQUBE_USERNAME: admin
      SONARQUBE_PASSWORD: pIn#h1E8
    networks:
      - devops_net
networks:
 devops_net:

